#!/bin/bash
# My first script


echo "print this shit"


wget -O genesis.json https://getbible.net/json?p=genesis&v=asv
wget -O exodus.json https://getbible.net/json?p=exodus&v=asv
wget -O leviticus.json https://getbible.net/json?p=leviticus&v=asv
wget -O numbers.json https://getbible.net/json?p=numbers&v=asv
wget -O deuteronomy.json https://getbible.net/json?p=deuteronomy&v=asv
wget -O joshua.json https://getbible.net/json?p=joshua&v=asv
wget -O judges.json https://getbible.net/json?p=judges&v=asv
wget -O ruth.json https://getbible.net/json?p=ruth&v=asv
wget -O 1sam.json https://getbible.net/json?p=1sam&v=asv
wget -O 2sam.json https://getbible.net/json?p=2sam&v=asv
wget -O 1kings.json https://getbible.net/json?p=1kings&v=asv
wget -O 2kings.json https://getbible.net/json?p=2kings&v=asv
wget -O 1chronicles.json https://getbible.net/json?p=1chronicles&v=asv
wget -O 2chronicles.json https://getbible.net/json?p=2chronicles&v=asv
wget -O ezra.json https://getbible.net/json?p=ezra&v=asv
wget -O nehemiah.json https://getbible.net/json?p=nehemiah&v=asv
wget -O esther.json https://getbible.net/json?p=esther&v=asv
wget -O job.json https://getbible.net/json?p=job&v=asv
wget -O psalms.json https://getbible.net/json?p=psalms&v=asv
wget -O proverbs.json https://getbible.net/json?p=proverbs&v=asv
wget -O ecclesiastes.json https://getbible.net/json?p=ecclesiastes&v=asv
wget -O songofsolomon.json https://getbible.net/json?p=songofsolomon&v=asv
wget -O isaiah.json https://getbible.net/json?p=isaiah&v=asv
wget -O jeremiah.json https://getbible.net/json?p=jeremiah&v=asv
wget -O lamentations.json https://getbible.net/json?p=lamentations&v=asv
wget -O ezekiel.json https://getbible.net/json?p=ezekiel&v=asv
wget -O daniel.json https://getbible.net/json?p=daniel&v=asv
wget -O hosea.json https://getbible.net/json?p=hosea&v=asv
wget -O joel.json https://getbible.net/json?p=joel&v=asv
wget -O amos.json https://getbible.net/json?p=amos&v=asv
wget -O obadiah.json https://getbible.net/json?p=obadiah&v=asv
wget -O jonah.json https://getbible.net/json?p=jonah&v=asv
wget -O micah.json https://getbible.net/json?p=micah&v=asv
wget -O nahum.json https://getbible.net/json?p=nahum&v=asv
wget -O habakkuk.json https://getbible.net/json?p=habakkuk&v=asv
wget -O zephaniah.json https://getbible.net/json?p=zephaniah&v=asv
wget -O haggai.json https://getbible.net/json?p=haggai&v=asv
wget -O zechariah.json https://getbible.net/json?p=zechariah&v=asv
wget -O malachi.json https://getbible.net/json?p=malachi&v=asv
wget -O matthew.json https://getbible.net/json?p=matthew&v=asv
wget -O mark.json https://getbible.net/json?p=mark&v=asv
wget -O luke.json https://getbible.net/json?p=luke&v=asv
wget -O john.json https://getbible.net/json?p=john&v=asv
wget -O acts.json https://getbible.net/json?p=acts&v=asv
wget -O romans.json https://getbible.net/json?p=romans&v=asv
wget -O 1corinthians.json https://getbible.net/json?p=1corinthians&v=asv
wget -O 2corinthians.json https://getbible.net/json?p=2corinthians&v=asv
wget -O galatians.json https://getbible.net/json?p=galatians&v=asv
wget -O ephesians.json https://getbible.net/json?p=ephesians&v=asv
wget -O philippians.json https://getbible.net/json?p=philippians&v=asv
wget -O colossians.json https://getbible.net/json?p=colossians&v=asv
wget -O 1thessalonians.json https://getbible.net/json?p=1thessalonians&v=asv
wget -O 2thessalonians.json https://getbible.net/json?p=2thessalonians&v=asv
wget -O 1timothy.json https://getbible.net/json?p=1timothy&v=asv
wget -O 2timothy.json https://getbible.net/json?p=2timothy&v=asv
wget -O titus.json https://getbible.net/json?p=titus&v=asv
wget -O philemon.json https://getbible.net/json?p=philemon&v=asv
wget -O hebrews.json https://getbible.net/json?p=hebrews&v=asv
wget -O james.json https://getbible.net/json?p=james&v=asv
wget -O 1peter.json https://getbible.net/json?p=1peter&v=asv
wget -O 2peter.json https://getbible.net/json?p=2peter&v=asv
wget -O 1john.json https://getbible.net/json?p=1john&v=asv
wget -O 2john.json https://getbible.net/json?p=2john&v=asv
wget -O 3john.json https://getbible.net/json?p=3john&v=asv
wget -O jude.json https://getbible.net/json?p=jude&v=asv
wget -O revelation.json https://getbible.net/json?p=revelation&v=asv

